- name: Playbook to execute ansible-lint and apply fixes as applicable
  hosts: localhost
  gather_facts: false
  become: false
  vars_files: 
    - vars.yml

  tasks:
    - name: Remove all local repos
      ansible.builtin.file:
        path: "{{ repo_path }}"
        state: absent
      
    - name: Get all the teams under an organisation
      ansible.builtin.uri:
        url: "https://api.github.com/orgs/ansible-automate/teams"
        headers:
          Accept: application/vnd.github+json
          Authorization: Bearer {{ githubtoken }}
          X-GitHub-Api-Version: 2022-11-28
        validate_certs: false
      register: team

    # This task will loop through all the teams under an organization
    - name: Looping through the teams
      ansible.builtin.include_tasks:
        file: tasks/git-repo.yml
      loop: "{{ team.json }}"
      loop_control:
        loop_var: gitteam
      when: team_name == "all"

    # This task will only  be called for the team name provided as part of survey or in var file
    - name: Looping through team {{ team_name }}
      ansible.builtin.include_tasks:
        file: tasks/git-repo.yml
      loop: "{{ team.json }}"
      loop_control:
        loop_var: gitteam
      when: gitteam.name == team_name
