---
- name: Git clone the repo and branch linted
  ansible.builtin.git:
    repo: "{{ url }}"
    dest: "{{ repo_path }}/{{ item.name }}"
    version: linted
  
- name: Delete prod_linted branch
  ansible.builtin.shell: |
    cd {{ repo_path }}/{{ item.name }}
    git push {{ url }} -d prod_linted

- name: Delete repo dir
  ansible.builtin.file:
    path: "{{ repo_path }}/{{ item.name }}"
    state: absent
