---
- name: Clone the repo with prod_linted branch
  ansible.builtin.git:
    repo: "{{ url }}"
    dest: "{{ repo_path }}/{{ item.name }}"
    version: prod_linted
  
- name: Delete branches prod_linted and prod_linted_noresult
  ansible.builtin.shell: |
    cd {{ repo_path }}/{{ item.name }}
    git push {{ url }} -d prod_linted
    git push {{ url }} -d prod_linted_noresult
 
- name: Delete repo dir
  ansible.builtin.file:
    path: "{{ repo_path }}/{{ item.name }}"
    state: absent