---
- name: Git clone the repo {{ item.name }} with branch {{ src_branch }}
  ansible.builtin.git:
    repo: "{{ url }}"
    dest: "{{ repo_path }}/{{ item.name }}"
    version: "{{ src_branch }}"
  
- name: Remove previous lint reports from branch {{ src_branch }}
  ansible.builtin.shell: |
    cd {{ repo_path }}/{{ item.name }}
    git config user.email "mrchandna@gmail.com"
    git config user.name "{{ awx_user_name }}"
    rm -f linted/*.txt
  ignore_errors: true
  when: src_branch == "linted"
  
- name: Checkout new branch named linted
  ansible.builtin.shell: |
    cd {{ repo_path }}/{{ item.name }}
    git config user.email "mrchandna@gmail.com"
    git config user.name "{{ awx_user_name }}"
    git checkout -b linted prod
    mkdir linted
  #ignore_errors: true
  when: src_branch == "prod"

- name: Task to look for YAML files to perform lint
  ansible.builtin.include_tasks:
    file: tasks/lint_files.yml
  
- name: Add and Commit linted files to linted branch and checkout new branch without text files for prod branch
  ansible.builtin.shell: |
    cd {{ repo_path }}/{{ item.name }}
    git add .
    git commit -m "Updated modules with FQCN, reformatted yaml and generated lint report"
    git push {{ url }} linted
    git checkout -b prod_linted linted
    rm -rf linted/
    git add .
    git commit -m "Updated modules with FQCN, reformatted yaml and generated lint report"
    git push {{ url }} prod_linted
  #ignore_errors: true
  when: src_branch == "prod"

- name: Add and Commit linted files to linted branch and checkout new branch without text files 
  ansible.builtin.shell: |
    cd {{ repo_path }}/{{ item.name }}
    git add .
    git commit -m "Updated modules with FQCN, reformatted yaml and generated lint report"
    git push {{ url }} linted
    git checkout -b prod_linted linted
    rm -rf linted/
    git add .
    git commit -m "Updated modules with FQCN, reformatted yaml and generated lint report"
    git push {{ url }} prod_linted
  ignore_errors: true
  when: src_branch == "linted"

- name: Create Pull Request from prod_linted to prod
  ansible.builtin.uri:
    url: https://api.github.com/repos/ansible-automate/{{ item.name }}/pulls
    headers:
      Accept: application/vnd.github+json
      Authorization: Bearer {{ githubtoken }}
      X-GitHub-Api-Version: 2022-11-28
    body_format: json
    body:
      title: Marge prod_linted to prod
      head: prod_linted
      base: prod
    validate_certs: false
    method: POST
    status_code: 201
