---
- name: Find YML files in repo {{ item.name }} for linting
  ansible.builtin.find:
    path: "{{ repo_path }}/{{ item.name }}"
    patterns: '*.yml'
    recurse: true 
  register: files

- name: Compute the file list
  ansible.builtin.set_fact:
    #file_list: "{{ files['files'] | map(attribute='path') | map('regex_replace','^.*/(.*)$','\\1') | list }}"
    file_list: "{{ files['files'] | map(attribute='path') | map('basename') | list }}"

- name: Execute lint on discovered files
  ansible.builtin.shell: |
    ansible-lint -q --nocolor -c ../../.ansible-lint {{ flist }} --exclude * --fix >> linted/{{ flist | regex_replace('.yml','') }}_report.txt 2>>linted/{{ flist | regex_replace('.yml','') }}_error.txt 
  args: 
    chdir: "{{ repo_path }}/{{ item.name }}"
  loop: "{{ file_list }}"
  loop_control:
    loop_var: flist
  ignore_errors: true